CREATE TABLE TRACK_DAY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UTENTE_ID INTEGER NOT NULL,
    AUTO_ID INTEGER NOT NULL,
    DATA_EVENTO TEXT NOT NULL, 
    ORA_INIZIO TEXT NOT NULL, 
    ORA_FINE TEXT NOT NULL,   
    CIRCUITO TEXT NOT NULL,
    PREZZO REAL NOT NULL,
    STATO TEXT NOT NULL,
    DATA_CREAZIONE TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (UTENTE_ID) REFERENCES UTENTI(ID),
    FOREIGN KEY (AUTO_ID) REFERENCES AUTO(ID)
);

