-- Tabella UTENTE
CREATE TABLE UTENTE (
    ID_utente INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cognome TEXT NOT NULL,
    data_nascita DATE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT null,
    ruolo TEXT NOT NULL CHECK (ruolo IN ('admin', 'utente'))
);

-- Tabella AUTO
CREATE TABLE AUTO (
    ID_auto INTEGER PRIMARY KEY AUTOINCREMENT,
    modello TEXT NOT NULL,
    marca TEXT NOT NULL,
    nazione TEXT NOT NULL,
    motore TEXT NOT NULL
);

-- Tabella PRENOTAZIONE
CREATE TABLE PRENOTAZIONE (
    ID_prenotazione INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_utente INTEGER NOT NULL,
    ID_auto INTEGER NOT NULL,
    data_prenotazione DATE NOT NULL,
    circuito TEXT,
    tipologia TEXT NOT NULL CHECK (tipologia IN ('trackday', 'noleggio')),
    FOREIGN KEY (ID_utente) REFERENCES UTENTE(ID_utente) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_auto) REFERENCES AUTO(ID_auto)
);

-- Tabella PAGAMENTI
CREATE TABLE PAGAMENTI (
    ID_pagamento INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_prenotazione INTEGER NOT NULL,
    ID_utente INTEGER NOT NULL,
    FOREIGN KEY (ID_prenotazione) REFERENCES PRENOTAZIONE(ID_prenotazione) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_utente) REFERENCES UTENTE(ID_utente) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabella RECENSIONI
CREATE TABLE RECENSIONI (
    ID_recensione INTEGER PRIMARY KEY AUTOINCREMENT,    
    ID_utente INTEGER NOT NULL,
    valutazione INTEGER NOT NULL,
    servizio TEXT NOT NULL,
    auto TEXT NOT NULL,
    contenuto TEXT NOT NULL,
    data_creazione TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (ID_utente) REFERENCES UTENTE(ID_utente) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabella TRACK-DAY
CREATE TABLE TRACK_DAY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_utente INTEGER NOT NULL,
    ID_auto INTEGER NOT NULL,
    ID_prenotazione INTEGER NOT NULL,
    DATA_EVENTO TEXT NOT NULL, 
    CIRCUITO TEXT NOT NULL,
    DATA_CREAZIONE TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (ID_utente) REFERENCES UTENTE(ID_utente) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_auto) REFERENCES AUTO(ID_auto) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_prenotazione) REFERENCES PRENOTAZIONE(ID_prenotazione) ON DELETE CASCADE ON UPDATE CASCADE
);
